### ISSUE TITLE
Wildcard match field

### ISSUE THREAD

**Issue by marcusleandro** [jkwakman/Open-Cookie-Database#11]
Hi, first of all thanks for the effort to make this useful database.

But when I was checking the csv I've noticed the last column "Wildcard match". I've seen in some cookies like _ga_ that subintentend that in the end of the cookie name could get the code that vary for each client, but How can I know where to complete the absent part? Its not clear for me. Have any insights?

Thanks in advance.

**Comment by Seikilos** [comment]
I don't have a complete answer to this as I also stumbled upon this (3 years later) but my assumption is: When it is a wildcard, you have to use a `myCookie.Contains(CookieWithWildcard)` operation instead of direct comparison like `myCookie == CookieWithoutWildcard`

**Comment by jkwakman** [comment]
The behavior is described in the docs see:

https://github.com/jkwakman/Open-Cookie-Database?tab=readme-ov-file#wildcard-match

@Seikilos assumption is right. Thank you for the feedback. 

Kind regards,

Jack Kwakman
