### ISSUE TITLE
Non-Cookie entries in the Database

### ISSUE THREAD

**Issue by hwgn** [jkwakman/Open-Cookie-Database#30]
There are currently three non-cookie entries in the DB, starting with [Line 163](https://github.com/jkwakman/Open-Cookie-Database/blob/240a3f89a119a2bd9c57d10b2bf5eca4a530525b/open-cookie-database.csv#L163). I suggest removing them as they carry no actual usable information (except that these services use JS Tags?) and may cause unexpected behavior in software utilizing the database.

Edit: Also just found a duplicate on [Line 455](https://github.com/jkwakman/Open-Cookie-Database/blob/240a3f89a119a2bd9c57d10b2bf5eca4a530525b/open-cookie-database.csv#L455) / [Line 458](https://github.com/jkwakman/Open-Cookie-Database/blob/240a3f89a119a2bd9c57d10b2bf5eca4a530525b/open-cookie-database.csv#L458).

**Comment by jkwakman** [comment]
Dear hwgn,

Thankyou for the valuable feedback. I have made changes in master to reflect you're recommendations. 

Kind regards,

Jack Kwakman
