### ISSUE TITLE
Duplicate Cookies

### ISSUE THREAD

**Issue by hwgn** [jkwakman/Open-Cookie-Database#33]
My tool reported some duplicated cookies, so I'll pass this info on (I can also fix this in a couple of days if nobody else has the time)

* `viewed_cookie_policy` is contained twice, with the same information.
* `OptanonConsent` is contained twice, with slightly varying information.

Additionally, these cookies are newly added with the same name of another cookie. This was bound to happen eventually (as nobody reserves cookie names), but either way, we might want to consider the implications of this for tools using the database - at least my tool currently searches cookies purely by name and will thus not see the second entry for this cookie.

* `tk_ai` is set both by WooCommerce and Jetpack with the exact same purpose. Perhaps we could merge these?
* `dpm`, served both by Adobe and demdex - unless one uses the other, this might not be able to be resolved
* `sp` by Quantcast and Snowplow. The descriptions hint towards the same use case, which might suggest both services having some sort of overlap in whatever sets this cookie

Open for discussion on how to proceed.

**Comment by jkwakman** [comment]
Dear Hendrik,

Thank you for the feedback. The duplicatie cookies are removed. 

- The tk_ai cookies is used by both platform for the same purpose and is assigned to both platforms in the same record.
- demdex is a domain now owned by Adobe. The demdex cookie has been removed
- Quantcast uses Snowplow so the sp cookie is also found on this domain. I have removed the Quantcase cookie. 

Thank you for the insights! 

Kind regards,

Jack Kwakman
