### ISSUE TITLE
Duplicate Cookies

### ISSUE THREAD

**Issue by hwgn** [jkwakman/Open-Cookie-Database#39]
Hello again,

My tool reported some more duplicated cookies, so I'll pass this info on. Happy to remove/fix them myself through a PR.

* `i` (`72ac111c-477f-484f-b97d-62870b65ae85` and `3b89dcd0-1da7-4382-8d20-a4c9eb614e00`) - once Yandex, once OpenX. This seems to be a genuine double usage. 
* `clientSrc` (`c3a9fc08-a42e-449c-8584-58580baa1e4f` & `a7d2b130-e322-4f4d-86c4-b2c86e8e7517`) - both Salesforce, one 1st Party, one 3rd
* `autocomplete` (`6cd0e40c-9cfc-4ce7-b9c4-7a312003d1bf` & `42219382-45ea-4f39-acfb-6da2df996eda`) - as above
* `disco` (`abcdaa07-7021-4979-a521-2afe3a7f1de3` & `00396982-e60c-4713-aa0c-c00ade38ff8d`) - as above
* `inst` (`461a5ae4-12cb-413e-8c06-3d899fdeb3b3` & `4a3c8234-e9b6-4f5f-bb2e-1943dfe3e95a`) - as above

If we normalize Domain-field to be empty to indicate Websites set this cookie to their own domain, I think it's fine to have duplicate names. Just right now, automated parsing of cookies that could be set to anywhere is near impossible to be 100% reliable.
If you agree, I could continue #21 and write a script to replace `Advertiser's website domain` and similar with empty fields.

**Comment by jkwakman** [comment]
Dear Hwgn,

Thank you for the feedback. Duplicate cookies are removed. For the removal of the 1st party domains I will have to check with some other users of this database.  

Kind regards,

Jack Kwakman

**Comment by hwgn** [comment]
Sounds good, and thanks!
