### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by raphigithub** [jkwakman/Open-Cookie-Database#7]
While checking the database I found some duplicates. Each of the following Name-Domain pairs exist twice, with the only difference being the description. Thus, I think that they should be merged.

Name	Domain
__atuvc	.addthis.com
__atuvs	.addthis.com
loc	        .addthis.com
obuid	outbrain.com
sb	        facebook.com (3rd party)
uvc	        .addthis.com

Anyway, thank you for your nice work in piling up the database, it is really helpful for making more sense out of some cookies. 

Best regards,
Raphael

**Comment by jkwakman** [comment]
Dear Raphael,

Thank you for the feedback. I have removed the duplicates. 

Kind regards,

Jack Kwakman
